POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "8 Blogs To Read When You Need A Little Inspiration",
    "author": "Deanna",
    "url": "https://lifebydeanna.com/8-blogs-to-read-when-you-need-a-little-inspiration/",
    "likes": 946
}