POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "THE IMPACT OF BITCOIN ON THE FINANCIAL SYSTEM",
    "author": "Ashok Patel",
    "url": "https://www.appsloveworld.com/the-impact-of-bitcoin-on-the-financial-system/",
    "likes": 946
}